### ISSUE TITLE
"Duplicate" examples seems to include discards

### ISSUE THREAD

**Issue by tybug** [tyche-pbt/tyche-extension#3]
While looking into https://github.com/HypothesisWorks/hypothesis/issues/3827, I found that the number of duplicates counted by Tyche was high (much higher than expected) when discards were in play. 245 + 76 = 321 gets us almost to 322 on the left, so I suspect discards are being folded into duplicates, probably along with an off by one error.

| with discards | without discards |
|-|-|
| <img width="610" alt="image" src="https://github.com/tyche-pbt/tyche-extension/assets/31628143/4a861d99-9ce9-4559-ae0b-5b1b95ecd598"> | <img width="619" alt="image" src="https://github.com/tyche-pbt/tyche-extension/assets/31628143/491f48e0-4947-4473-a24a-f26289387916"> |

My intuitive interpretation of "duplicate" is "a fully formed, valid test case was identical" — but maybe you think of it differently!

Let me know if reports like this are not helpful or useful while Tyche is still in early alpha.

**Comment by hgoldstein95** [comment]
Oh interesting! I think we just had different intuition for how those numbers should be interpreted. Here's how I was imagining those four boxes, pictorially:
![IMG_1413](https://github.com/tyche-pbt/tyche-extension/assets/8687298/4f4195b4-d624-438e-a38d-5256d611526a)
Basically, "discarded" means everything (duplicate and not) that was discarded, and "duplicate" means everything (discarded and not) that was a duplicate. But maybe this isn't what users care about? I suppose we could show a mosaic chart like this one that I just drew, but when I tested that out it seemed a bit confusing.

What do you think you'd want to see? I also have another interview today, I'll see if I can ask how they interpreted these numbers / which ones they'd want to see.

**Comment by hgoldstein95** [comment]
Oh and issues here are good! It makes sense to have them in one place, I think.

**Comment by tybug** [comment]
Hmm. When opening this issue I thought that the discarded samples in my test case didn't even have a valid string representation, since presumably they overran their buffer in the middle of generation. I suspected that these were being parsed as the empty string and counted as duplicates when I thought it would be more appropriate to discard them. But looking at my `testcases.jsonl` file, all the `gave_up` cases seem to have valid/filled `arguments` fields! I'll have to spend more time looking into why. 

Taking a step back, it seems there are broadly two kinds of `gave_up`:

1. Gave up during test case creation (e.g., overran buffer in the middle of generation)
2. Gave up after test case creation, but before completely executing the test function (e.g. `assume` in user code)

I would consider it a bug to consider (1) as duplicates...but we still want to report them as discards. This does complicate the chart you drew: we could add a third row for "so invalid we can't represent it", alongside the existing "valid" and "invalid" rows. But the "discard" column only makes sense for "valid" and "invalid", so the bottom rightmost square may become greyed out, so to speak.

**Comment by tybug** [comment]
To answer the question more directly: I think all four squares in your chart are useful, where the "invalid" row is taken to mean "invalid, but with a representable test case". But the existence of "invalid, but without a representable test case" — perhaps because we overran the buffer before we finished generating it — complicates things.

I don't know the best way to display any of this, but I'll leave that to the experts 😄

**Comment by hgoldstein95** [comment]
Point well taken. I'll play around with some better ways of displaying these different categories. It's possible that treating `gave_up && repr == ""` differently from `gave_up && repr != ""` could also solve the issue we were discussing in the hypothesis thread as well.

**Comment by hgoldstein95** [comment]
@tybug How does this look?
<img width="467" alt="image" src="https://github.com/tyche-pbt/tyche-extension/assets/8687298/f4dd4def-65a3-4756-8fcf-32d72216be67">

**Comment by Zac-HD** [comment]
There are actually *three* 'amounts of repr' we can hit: 

1. Complete repr -> passed, or failed, or `assume(False)` after generating all data
2. No repr -> gave_up before invoking the user's test function
3. Partial repr -> gave_up due to `assume(False)` after invoking the user's test function, so we have all the arguments but perhaps not all the interactive draws (from `st.data()`, `st.randoms()`, `st.functions()`, etc.)

So we should explicitly tell the user that the repr or analysis we do in the gave_up case is based on incomplete information, and add something like this comment to the docs on the Hypothesis side!

**Comment by Zac-HD** [comment]
Counting unique examples by repr is also lossy in both directions: at times we'll overcount based on some reprs including the memory address or other inessential details\*, but we can also undercount by seeing equal reprs for distinct values (e.g. certain NaNs, Unicode normalization, etc.).  Two things we can do about that:

1. Have Hypothesis string-replace all memory addresses with incrementing integers in the string output, so we preserve object identity but normalize the locations.  This is annoying but feasible to do in the pretty-printer or as a post-processing step for observability (I favor the latter), and fixes the most common cause of overcounting.  However, due to (2) it also doesn't matter much!

2. Almost everything we generate is unique up to the choice sequence which generated it, so duplicate values are usually because the strategy is an injective function from choice sequence to value.  I think the best thing to do here is reduce that redundancy by moving over to our new IR, which @tybug and I (mostly Liam!) are working on.  In principle we could also do some choice-sequence-based counting *ala* explain-phase/Inquisitor, but I'm not sure it would help and certainly wouldn't be generalizable to other PBT libraries.

Overall I think I'd just add a circled-i note which explains that the count is a heuristic based on reprs and might not be fully accurate.

**Comment by tybug** [comment]
> @tybug How does this look?

I like it visually 🙂 but what is intended by the intersection of `Gave Up` and `Duplicate`? To me `Discarded == full repr` and `Gave Up == no repr`. I still have the same confusion of "how can we tell if test cases with no repr are duplicates?" as before. In other words, it seems the `Gave Up` bar should be a single bar, and not segmented. But maybe I'm misunderstanding something?

**Comment by hgoldstein95** [comment]
@tybug  I've been using `repr + arguments` to compute uniqueness, so there are things that are "Gave Up" (no `repr`) that aren't all the same. Does that seem like a reasonable distinction? Is it not worth the trouble?

@Zac-HD I think a note that makes it clear that counts are heuristic makes sense to me. Is there anything else on my side that needs to be changed, in your opinion?

**Comment by Zac-HD** [comment]
If you're using arguments as part of the uniqueness computation, check that `NaN` is handled properly?  e.g. you probably want `nan, nan, 1` to count as two rather than three distinct cases.

**Comment by tybug** [comment]
> I've been using repr + arguments to compute uniqueness

aha, I see. That was my confusion, thanks! I can't say I have a full understanding of how `arguments` is computed in the three different "repr progress" cases @Zac-HD listed (e.g. what happens to unfinished arguments when the buffer is overrun? do we fill it out with the zero buffer?), so my opinion should not count for much, but this makes sense to me. I'll have to read that part of the Hypothesis code in more detail.

**Comment by Zac-HD** [comment]
> e.g. what happens to unfinished arguments when the buffer is overrun? do we fill it out with the zero buffer?

We immediately abort the test on overrun, and so unfinished arguments are not added to our observability report, but previously-finished arguments will be there.  Note that everything generated inside `@given()`/before invoking the user's test function is generated and then added to the report as a single chunk.  For example:

```python
@given(
    st.data(),
    st.integers().filter(bool),  # if we abandon here, no arguments at all (not even data())
)
def test(data, x):
    assume(x > 1)  # if we give up here, we'll have arguments x and data in our dict but not the interactive draw
    data.draw(...)  # if we give up here, same as the line above
    assume(...)  # arguments will be complete, because no more draws were possible, but we can't tell
    assert ... # pass or fail, arguments will be complete
    # Since we didn't give up, we also get a nonempty repr here.
```
